<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estadousuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estadousuario_model');
    } 

    /*
     * Listing of estadousuario
     */
    function index()
    {
        
        
        $this->load->view('header',['title'=>"Listado de estados"]);
        $this->load->view('estadousuario/index',['estadousuario'=>$this->Estadousuario_model->get_all_estadousuario()]);
        $this->load->view('footer');
    }

    /*
     * Adding a new estadousuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'descripcion' => $this->input->post('descripcion'),
                'nombre' => $this->input->post('nombre'),
            );
            
            $estadousuario_id = $this->Estadousuario_model->add_estadousuario($params);
            redirect('estadousuario/index');
        }
        else
        {   $this->load->view("header",["title"=>"Registro estado"]);
            $this->load->view('estadousuario/add');
            $this->load->view('footer');
        }
    }  

    /*
     * Editing a estadousuario
     */
    function edit($nombre)
    {   
        // check if the estadousuario exists before trying to edit it
        $data['estadousuario'] = $this->Estadousuario_model->get_estadousuario($nombre);
        
        if(isset($data['estadousuario']['nombre']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Estadousuario_model->update_estadousuario($nombre,$params);            
                redirect('estadousuario/index');
            }
            else
            {
                $data['_view'] = 'estadousuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The estadousuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting estadousuario
     */
    function remove($nombre)
    {
        $estadousuario = $this->Estadousuario_model->get_estadousuario($nombre);

        // check if the estadousuario exists before trying to delete it
        if(isset($estadousuario['nombre']))
        {
            $this->Estadousuario_model->delete_estadousuario($nombre);
            redirect('estadousuario/index');
        }
        else
            show_error('The estadousuario you are trying to delete does not exist.');
    }
    
}
