<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rol extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rol_model');
    } 

    /*
     * Listing of rol
     */
    function index()
    {
        $data['rol'] = $this->Rol_model->get_all_rol();
        
        $data['_view'] = 'rol/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rol
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $rol_id = $this->Rol_model->add_rol($params);
            redirect('rol/index');
        }
        else
        {            
            $data['_view'] = 'rol/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rol
     */
    function edit($nombre)
    {   
        // check if the rol exists before trying to edit it
        $data['rol'] = $this->Rol_model->get_rol($nombre);
        
        if(isset($data['rol']['nombre']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Rol_model->update_rol($nombre,$params);            
                redirect('rol/index');
            }
            else
            {
                $data['_view'] = 'rol/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rol you are trying to edit does not exist.');
    } 

    /*
     * Deleting rol
     */
    function remove($nombre)
    {
        $rol = $this->Rol_model->get_rol($nombre);

        // check if the rol exists before trying to delete it
        if(isset($rol['nombre']))
        {
            $this->Rol_model->delete_rol($nombre);
            redirect('rol/index');
        }
        else
            show_error('The rol you are trying to delete does not exist.');
    }
    
}
