<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tenerusuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tenerusuario_model');
    } 

    /*
     * Listing of tenerusuario
     */
    function index()
    {
        
        $this->load->view('header',["title"=>"Historial de estados de los usuarios"]);
        $this->load->view('tenerusuario/index',array('tenerusuario'=>$this->Tenerusuario_model->get_all_tenerusuario()));
        $this->load->view('footer');
    }

    /*
     * Adding a new tenerusuario
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)     
        {   
           
           
                $params = array(
                    'nombreUsuario' => $_POST['nombreUsuario'],
                    'nombreEstadoUsuario'=>$_POST['nombreEstadoUsuario'],
                    'fecha' => $_POST['fecha'],
                    'hora' => $_POST['hora'],
                );
                $insercion = $this->Tenerusuario_model->add_tenerusuario($params);
            
            
            

            /*if($insercion){
                redirect('usuario/index');
            }else{
                echo "Ah ocurrido un error verifique que el estado exista";
            }*/
        }else{
        
         $this->load->view('header',["title"=>'asd']);
            
            $this->load->view('tenerusuario/add');
            $this->load->view('footer');
        }
        
    }  

    /*
     * Editing a tenerusuario
     */
    function edit()
    
    {   
        $nombreUsuario=$_POST["nombreUsuario"];
        $fecha=$_POST["fecha"];
        $hora=$_POST["hora"];
        // check if the tenerusuario exists before trying to edit it
        $data['tenerusuario'] =$this->Tenerusuario_model->get_tenerusuario($nombreUsuario,$fecha,$hora) ;
        
        if(isset($data['tenerusuario']['nombreUsuario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					
					'fechaFin' => getdate()["year"].":".getdate()["mon"].":".getdate()["mday"],
                );

                $this->Tenerusuario_model->update_tenerusuario($hora,$fecha,$nombreUsuario,$params);
                  
                           
                //redirect('tenerusuario/index');
            }
            else
            {
                $this->load->view('header',['title'=>'Edicion']);
                $this->load->view('tenerusuario/edit',array('tenerusuario'=>$data['tenerusuario']));
                $this->load->view('footer');
                
            }
        }
        else
            show_error('The tenerusuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting tenerusuario
     */
    function remove($hora)
    {
        $tenerusuario = $this->Tenerusuario_model->get_tenerusuario($hora);

        // check if the tenerusuario exists before trying to delete it
        if(isset($tenerusuario['hora']))
        {
            $this->Tenerusuario_model->delete_tenerusuario($hora);
            redirect('tenerusuario/index');
        }
        else
            show_error('The tenerusuario you are trying to delete does not exist.');
    }
    
}
