<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tenerusuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tenerusuario_model');
    } 

    /*
     * Listing of tenerusuario
     */
    function index()
    {
        $data['tenerusuario'] = $this->Tenerusuario_model->get_all_tenerusuario();
        
        $data['_view'] = 'tenerusuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tenerusuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombreUsuario' => $this->input->post('nombreUsuario'),
				'nombreEstadoUsuario' => $this->input->post('nombreEstadoUsuario'),
				'fechaFin' => $this->input->post('fechaFin'),
            );
            
            $tenerusuario_id = $this->Tenerusuario_model->add_tenerusuario($params);
            redirect('tenerusuario/index');
        }
        else
        {            
            $data['_view'] = 'tenerusuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tenerusuario
     */
    function edit($hora)
    {   
        // check if the tenerusuario exists before trying to edit it
        $data['tenerusuario'] = $this->Tenerusuario_model->get_tenerusuario($hora);
        
        if(isset($data['tenerusuario']['hora']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombreUsuario' => $this->input->post('nombreUsuario'),
					'nombreEstadoUsuario' => $this->input->post('nombreEstadoUsuario'),
					'fechaFin' => $this->input->post('fechaFin'),
                );

                $this->Tenerusuario_model->update_tenerusuario($hora,$params);            
                redirect('tenerusuario/index');
            }
            else
            {
                $data['_view'] = 'tenerusuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tenerusuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting tenerusuario
     */
    function remove($hora)
    {
        $tenerusuario = $this->Tenerusuario_model->get_tenerusuario($hora);

        // check if the tenerusuario exists before trying to delete it
        if(isset($tenerusuario['hora']))
        {
            $this->Tenerusuario_model->delete_tenerusuario($hora);
            redirect('tenerusuario/index');
        }
        else
            show_error('The tenerusuario you are trying to delete does not exist.');
    }
    
}
