<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Usuario extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    }

    /*
     * Listing of usuario
     */
    public function index()
    {
        $usuario = $this->Usuario_model->get_all_usuario();
        $this->load->view("header", ["title" => "Administrar usuarios", 'usuario' => $usuario]);
        $this->load->view('usuario/index');
        $this->load->view("footer");
    }

    /*
     * Adding a new usuario
     */
    public function registro()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'clave' => hash('sha224', $this->input->post('clave')),
                'dni' => $this->input->post('dni'),
                'apellido' => $this->input->post('apellido'),
                'nombre' => $this->input->post('nombre'),
                'domicilio' => $this->input->post('domicilio'),
                'email' => $this->input->post('email'),
                'nombreUsuario' => $this->input->post('nombreUsuario'),
            );

            $insercion = $this->Usuario_model->add_usuario($params);
            if ($insercion) {
                // $estado=new Tenerusuario();
                $fecha = (getdate()["year"]) . "-" . (getdate()["mon"]) . "-" . (getdate()["mday"]);
                $hora = (getdate()["hours"]) . ":" . (getdate()["minutes"]) . ":" . (getdate()["seconds"]);
                $nombreEstadoUsuario = "pendiente";
                $nombreUsuario = $params["nombreUsuario"];
                $post = array("fechaInicio"=>$fecha,"hora"=>$hora,"nombreUsuario"=>$nombreUsuario,"nombreEstadoUsuario"=>$nombreEstadoUsuario);
                $ch = curl_init(base_url() . "tenerusuario/add");
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));
                // execute!
                $response = curl_exec($ch);
                // close the connection, release resources used
                curl_close($ch);
                // do anything you want with your response
                if ($response) {
                    //$estado->add();
                    $this->load->view("header", ["title" => "Registro"]);
                    $this->load->view('inicio/registrarse', array("mensaje" => "Registrado con exito"));
                    $this->load->view("footer");
                }

            } else {
                $this->load->view("header", ["title" => "Registro"]);
                $this->load->view('inicio/registrarse', array("mensaje" => "El usuario ya existe"));
                $this->load->view("footer");
            }

            // redirect('usuario/index');
        } else {

            $this->load->view("header", ["title" => "Registro"]);
            $this->load->view('inicio/registrarse');

            $this->load->view("footer");
        }
    }

    /*
     * Editing a usuario
     */
    public function edit($nombreUsuario)
    {
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($nombreUsuario);

        if (isset($data['usuario']['nombreUsuario'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'clave' => $this->input->post('clave'),
                    'dni' => $this->input->post('dni'),
                    'apellido' => $this->input->post('apellido'),
                    'nombre' => $this->input->post('nombre'),
                    'domicilio' => $this->input->post('domicilio'),
                    'email' => $this->input->post('email'),
                );

                $this->Usuario_model->update_usuario($nombreUsuario, $params);
                redirect('usuario/index');
            } else {
                $data['_view'] = 'usuario/edit';
                $this->load->view("header", ["title" => "Editar Usuario"]);
                $this->load->view('layouts/main', $data);
                $this->load->view("footer");
            }
        } else {
            show_error('The usuario you are trying to edit does not exist.');
        }

    }

    /*
     * Deleting usuario
     */
    public function remove($nombreUsuario)
    {
        $usuario = $this->Usuario_model->get_usuario($nombreUsuario);

        // check if the usuario exists before trying to delete it
        if (isset($usuario['nombreUsuario'])) {
            if ($this->Usuario_model->delete_usuario($usuario['nombreUsuario'])) {

            } else {
                echo "nop";
            };
            //redirect("usuario/index");
        } else {
            show_error('The usuario you are trying to delete does not exist.');
        }

    }

}
