<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Usuario extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->helper('url');
        $this->load->library("session");
        $this->load->helper("form");
        $this->load->model("EstadoUsuario_model");
        $this->load->model("TieneRol_model");
        $this->load->model("TenerEstadoUsuario_model");
        $this->load->library("pagination");
    }
    
   
    /*
      * Lista a los usuarios que son de rol profesor
    */
    public function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usuario/index?');
        $config['total_rows'] = $this->Usuario_model->get_all_usuario_count();
        $this->pagination->initialize($config);
        $data['usuario'] = $this->Usuario_model->get_all_usuario($params);
        $this->load->view('header', array("title"=>"Lista de Usuarios"));
        $this->load->view('usuario/index', $data);
        $this->load->view("footer");
    }
    
    public function listaAdmin()
    {
        $data['usuario'] = $this->Usuario_model->get_all_usuario();
        $this->load->view('header', array("title"=>"Lista de Usuarios"));
        $this->load->view('usuario/listaAdmin', $data);
        $this->load->view("footer");
    }
    
    private function verificarToken($nroToken, $nombreUsuario)
    {
        $token=$this->TokenRecupera_model->get_tokenrecupera($nroToken, array("nombreUsuario"=>$nombreUsuario));
        $tokenR=$this->TenerEstadoToken_model->get_tenerestadotoken($nroToken);
        if ($tokenR!=null && $token!=null) {
            if ($tokenR["nombreEstadoToken"]=="pendiente" && $tokenR["fechaFin"]==null) {
                $res=true;
            } else {
                $res=false;
            }
        } else {
            $res=false;
        }
        return $res;
    }

    /*
     * Añadiendo a nuevo usuario
     */
    public function registro()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'clave' => hash('sha224', $this->input->post('clave')),
                'dni' => $this->input->post('dni'),
                'apellido' => $this->input->post('apellido'),
                'nombre' => $this->input->post('nombre'),
                'estudio' => $this->input->post('estudio'),
                'email' => $this->input->post('email'),
                'nombreUsuario' => $this->input->post('nombreUsuario'),
            );
            $insercion = $this->Usuario_model->add_usuario($params);
            if ($insercion) {
                $fecha = (getdate()["year"]) . "-" . (getdate()["mon"]) . "-" . (getdate()["mday"]);
                $hora = (getdate()["hours"]) . ":" . (getdate()["minutes"]) . ":" . (getdate()["seconds"]);
                $nombreEstadoUsuario = "pendiente";
                $nombreRol="Profesor";
                $nombreUsuario = $params["nombreUsuario"];
                $datosEstado = array("fechaInicio"=>$fecha,"hora"=>$hora,"nombreUsuario"=>$nombreUsuario,"nombreEstadoUsuario"=>$nombreEstadoUsuario);
                $datosRol=array("fechaInicio"=>$fecha,"nombreUsuario"=>$nombreUsuario,"nombreRol"=>$nombreRol);
                $insercionEstado = $this->TenerEstadoUsuario_model->add_tenerEstadoUsuario($datosEstado);
                $insercionProfesor = $this->Tienerol_model->add_tienerol($datosRol);
                $this->load->view("header", ["title" => "Registro"]);
                $this->load->view('inicio/registrarse', array("mensaje" => '<div class="alert alert-success text-center"><h4>'."Se ah registrado correctamente espere a que un administrador valide su cuenta".'</h4></div>'));
                $this->load->view("footer");
            } else {
                $this->load->view("header", ["title" => "Registro"]);
                $this->load->view('inicio/registrarse', array("mensaje" => '<div class="alert alert-info text-center"><h4>'."El usuario ya existe".'</h4></div>'));
                $this->load->view("footer");
            }
            // redirect('usuario/index');
        } else {
            $this->load->view("header", ["title" => "Registro","scripts"=>["validacion"]]);
            $this->load->view('inicio/registrarse');
            $this->load->view("footer");
        }
    }

    /*
     * Editando a el estado y el rol del usuario
     */
    /*
     * Editing a usuario
     */
    public function edit($nombreUsuario)
    {
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($nombreUsuario);
        
        if (isset($data['usuario']['nombreUsuario'])) {
            $this->load->library('form_validation');
            if (!$this->input->post('roles') ||  !$this->input->post('estados')) {
                $this->form_validation->set_rules('clave', 'Clave', 'required|max_length[70]');
                $this->form_validation->set_rules('dni', 'Dni', 'integer');
                $this->form_validation->set_rules('apellido', 'Apellido', 'required|max_length[30]');
                $this->form_validation->set_rules('nombre', 'Nombre', 'required|max_length[30]');
                $this->form_validation->set_rules('estudio', 'Estudio', 'required|max_length[50]');
                $this->form_validation->set_rules('email', 'Email', 'required|max_length[50]|valid_email');
                if ($this->form_validation->run()) {//Cambiamos datos especificos
                    $params = array(
                    'clave' => $this->input->post('clave'),
                    'dni' => $this->input->post('dni'),
                    'apellido' => $this->input->post('apellido'),
                    'nombre' => $this->input->post('nombre'),
                    'estudio' => $this->input->post('estudio'),
                    'email' => $this->input->post('email'),
                    
                );
                    $this->Usuario_model->update_usuario($nombreUsuario, $params);
                    redirect('usuario/index');
                } else {
                    $this->load->view('header', array("title"=>"Editar usuario"));
                    $this->load->view('usuario/edit', $data);
                    $this->load->view("footer");
                }
            } else {//Cambiamos rol y estado
                
                $rol=$this->input->post('roles');
                $estado= $this->input->post('estados');
                if (strtolower($estado)=="alta") {
                    if ($this->mailAlta($nombreUsuario, $this->input->post('email'))) {
                        ?>
<script>
    alert("enviado");
</script><?php
                    }
                }
                $this->TieneRol_model->update_tienerol(array("fechaFin"=>date("Y-m-d")), array("nombreUsuario"=>$nombreUsuario,"fechaFin"=>null));
                $this->TieneRol_model->add_tienerol(array("fechaInicio"=>date("Y-m-d"),"hora"=>date("H:i:s"),"nombreUsuario"=>$nombreUsuario,"nombreRol"=>$rol));
                $this->TenerEstadoUsuario_model->update_tenerEstadoUsuario(array("fechaFin"=>date("Y-m-d")), array("nombreUsuario"=>$nombreUsuario,"fechaFin"=>null));
                $this->TenerEstadoUsuario_model->add_tenerEstadoUsuario(array("fechaInicio"=>date("Y-m-d"),"hora"=>date("H:i:s"),"nombreUsuario"=>$nombreUsuario,"nombreEstadoUsuario"=>$estado));
                redirect('usuario/index');
            }
        } else {
            show_error('The usuario you are trying to edit does not exist.');
        }
    }
    private function mailAlta($nombreUsuario, $email)
    {
        $this->load->library("PHPMailer");
        $mail = $this->phpmailer->load();
        $mail->From = "rea@not-reply.com";
        $mail->IsSMTP();
        $mail->CharSet="UTF-8";
        $mail->SMTPSecure = 'tls';
        $mail->Host = 'smtp.gmail.com';
        $mail->Port = 587;
        $mail->Username = 'santiago.navarro@est.fi.uncoma.edu.ar';
        $mail->Password = '38365920s';
        $mail->SMTPAuth = true;
        $mail->FromName = "Rea";
        //To address and name
        $mail->addAddress($email);
        //$mail->addAddress("recepient1@example.com"); //Recipient name is optional

        //Address to which recipient will reply
        $mail->addReplyTo("santiago.navarro@est.fi.uncoma.edu.ar", "Reply");

        //Send HTML or Plain Text email
        $mail->isHTML(true);
        $mensaje='Bienvenido a la plataforma Rea su usuario ha sido dado de alta ingrese su usuario y contraseña en '.base_url().'login ';
        $mail->Subject ="Usuario validado";
        $mail->Body = $mensaje;
        $mail->AltBody = $mensaje;
        echo "<span class='fa fa-spinner fa-spin'></span>";
        if (!$mail->send()) {
            
           // echo "Mailer Error: " . $mail->ErrorInfo;
            $envio=false;
        } else {
            $envio=true;
        }
        return $envio;
    }
 
    /**
     * Funcion auxiliar encargada de modificar el estado o el rol segun corresponda
     * donde $datos corresponde a un array asociativo donde entraran las claves tabla,nombreUsuario,antiguo,nuevo
     */
    private function actualizar($datos)
    {
        $fechaActual=getdate()["year"]."-".getdate()["mon"]."-".getdate()["mday"];
        $horaActual=getdate()["hours"].":".getdate()["minutes"].":".getdate()["seconds"];
        $actualizacion=true;
        if ($datos["antiguo"]!=$datos["nuevo"]) {
            $params = array(
                    'nombreUsuario'=>$datos["nombreUsuario"],
                    'nombre'.$datos["tabla"]=>$datos["nuevo"],
                    'fechaInicio'=>$fechaActual,
                    'hora'=>$horaActual,
                );
            switch ($datos["tabla"]) {
                    case "EstadoUsuario":
                    $setAntiguoEst=$this->TenerEstadoUsuario_model->update_tenerEstadoUsuario(array('fechaFin'=>$fechaActual), array('nombreEstadoUsuario'=>$datos["antiguo"],'nombreUsuario'=>$datos["nombreUsuario"],'fechaFin'=>null));
                    if ($setAntiguoEst) {
                        $insertEstado=$this->TenerEstadoUsuario_model->add_tenerEstadoUsuario($params);
                        if (!$insertEstado) {//Si por algun motivo fallo la insercion vuelve a null la fecha fin del ultimo estado
                            $this->TenerEstadoUsuario_model->update_tenerEstadoUsuario(array('fechaFin'=>null), array('nombreEstadoUsuario'=>$datos["antiguo"],'nombreUsuario'=>$nombreUsuario,'fechaFin'=>$fechaActual));
                            $actualizacion=false;
                        }
                    } else {
                        $actualizacion=false;
                    }
                    break;
                    case "Rol":
                     $setAntiguoRol=$this->Tienerol_model->update_tienerol(array('fechaFin'=>$fechaActual), array('nombreRol'=>$datos["antiguo"],'nombreUsuario'=>$datos["nombreUsuario"],'fechaFin'=>null));
                    if ($setAntiguoRol) {
                        $insertRol=$this->Tienerol_model->add_tienerol($params);
                        if (!$insertRol) {//Si por algun motivo fallo la insercion vuelve a null la fecha fin del ultimo rol
                            $this->Tienerol_model->update_tienerol(array('fechaFin'=>null), array('nombreRol'=>$datos["antiguo"],'nombreUsuario'=>$datos["nombreUsuario"],'fechaFin'=>$fechaActual));
                            $actualizacion=false;
                        }
                    } else {
                        $actualizacion=false;
                    }
                    break;
                }
        }
        return $actualizacion;
    }
  
    /**
     * Editar perfil del usuario
     * El usuario va a poder modificar sus datos, por si quiere modificar o agregar alguno de estos.
     */
    public function editarPerfil()
    {
        $cant=count($_POST);
        if ($cant>0) {//Se enviaron datos desde el formulario
            $nombUser=$this->input->post("nombreUsuario");
            $nombUser=$this->session->nombreUsuario;
            $nombre=$this->input->post("nombre");
            $apellido=$this->input->post("apellido");
            $domicilio=$this->input->post("domicilio");
            $dni=$this->input->post("dni");
            $email=$this->input->post("email");
            $foto=$_FILES["foto"];
            $estudio=$this->input->post("estudio");
            $clave=$this->input->post("clave");
            $claveNueva=$this->input->post("clave1");
            $claveNuevaRep=$this->input->post("clave2");

            $rutas=["./assets/upload/","./assets/upload/fotoPerfil","./assets/upload/fotoPerfil/".$this->session->nombreUsuario];
            foreach ($rutas as $unaRuta) {
                if (!is_dir($unaRuta)) {
                    mkdir($unaRuta, 0777, true);
                }
            }
            move_uploaded_file($foto['tmp_name'], "./assets/upload/fotoPerfil/".$this->session->nombreUsuario."/".$foto["name"]);
            $usuarioBuscado=$this->Usuario_model->get_usuario($nombUser);
            if ($usuarioBuscado!=null) {
                $existeMail=$this->Usuario_model->get_usuario("", array("usuario.email"=>$this->input->post("email")));
                if (hash('sha224', $clave)==$usuarioBuscado["clave"] && ($existeMail==null || $email==$this->session->email)) {
                    if ($claveNueva!="" && $claveNueva==$claveNuevaRep) {
                        if ($foto["name"]=="") {
                            $imagen=$this->session->foto;
                        } else {
                            $imagen=$foto["name"];
                        }
                        $datos=["foto"=>$imagen,"nombre"=>$nombre,"apellido"=>$apellido,"estudio"=>$estudio,"dni"=>$dni,"email"=>$email,"clave"=>hash('sha224', $claveNueva)];
                        $res=$this->Usuario_model->update_usuario($nombUser, $datos);//Estaba por aca
                        
                        if ($res) {
                            $this->actualizarSesion($datos);
                            $this->load->view("header", ["title" => "Editar Perfil"]);
                            $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-success text-center"><h4>'.'Datos Actualizados Correctamente'.'</h4></div>']);
                            $this->load->view("footer");
                        } else {
                            $this->load->view("header", ["title" => "Editar Perfil"]);
                            $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'Error al tratar de cargar los datos'.'</h4></div>']);
                            $this->load->view("footer");
                        }
                    } elseif ($claveNueva!=$claveNuevaRep) {
                        $this->load->view("header", ["title" => "Editar Perfil"]);
                        $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'Las claves no coinciden'.'</h4></div>']);
                        $this->load->view("footer");
                    } else {
                        if ($foto["name"]=="") {
                            $imagen=$this->session->foto;
                        } else {
                            $imagen=$foto["name"];
                        }
                        $datos=["foto"=>$imagen,"nombre"=>$nombre,"apellido"=>$apellido,"estudio"=>$estudio,"dni"=>$dni,"email"=>$email,"clave"=>hash('sha224', $clave)];
                        $res=$this->Usuario_model->update_usuario($nombUser, $datos);//Estaba por aca
                    
                        if ($res) {
                            $this->actualizarSesion($datos);
                            $this->load->view("header", ["title" => "Editar Perfil"]);
                            $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-success text-center"><h4>'.'Datos Actualizados Correctamente'.'</h4></div>']);
                            $this->load->view("footer");
                        } else {
                            $this->load->view("header", ["title" => "Editar Perfil"]);
                            $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'Error al tratar de cargar los datos'.'</h4></div>']);
                            $this->load->view("footer");
                        }
                    }
                } elseif ($existeMail!=null) {
                    $this->load->view("header", ["title" => "Editar Perfil"]);
                    $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'El email ya existe'.'</h4></div>']);
                    $this->load->view("footer");
                } else {
                    $this->load->view("header", ["title" => "Editar Perfil"]);
                    $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'La clave actual es invalida'.'</h4></div>']);
                    $this->load->view("footer");
                }
            } else {
                $this->load->view("header", ["title" => "Editar Perfil"]);
                $this->load->view('usuario/editarPerfil', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'El usuario no existe'.'</h4></div>']);
                $this->load->view("footer");
            }
        } else {
            $this->load->view("header", ["title" => "Editar Perfil"]);
            $this->load->view('usuario/editarPerfil');
            $this->load->view("footer");
        }
    }
    private function actualizarSesion($datos)
    {
        $_SESSION["nombre"]=$datos["nombre"];
        $_SESSION["apellido"]=$datos["apellido"];
        $_SESSION["estudio"]=$datos["estudio"];
        $_SESSION["dni"]=$datos["dni"];
        $_SESSION["foto"]=$datos["foto"];
        $_SESSION["email"]=$datos["email"];
        $_SESSION["clave"]=$datos["clave"];
    }
    /*
     * Eliminar un usuario
     */
    public function eliminarCuenta($nombUser="")
    {
        if ($nombUser=="") {
            $this->load->view("header", ["title" => "Eliminar Cuenta"]);
            $this->load->view('usuario/eliminarCuenta');
            $this->load->view("footer");
        } else {
            $hora=date("H:i:s");
            $fecha=date("Y-m-d");
            $paramsUpdate=array("fechaFin"=>date("Y-m-d"));
            $paramsNew=array("nombreEstadoUsuario"=>"baja","fechaFin"=>null,"fechaInicio"=>$fecha,"nombreUsuario"=>$nombUser,"hora"=>$hora);
            $where=array("fechaFin"=>null,"nombreUsuario"=>$nombUser,"nombreEstadoUsuario"=>"alta");
            $actualizarEstado=$this->TenerEstadoUsuario_model->update_tenerestadousuario($paramsUpdate, $where);
            if ($actualizarEstado) {
                $nuevoEstado=$this->TenerEstadoUsuario_model->add_tenerEstadoUsuario($paramsNew);
                if ($nuevoEstado) {
                    session_destroy();
                    redirect('login/cerrarSession');
                } else {
                    $this->load->view("header", ["title" => "Eliminar Cuenta"]);
                    $this->load->view('usuario/eliminarCuenta', ['mensaje'=>'<div class="offset-md-3 col-md-6 alert alert-danger text-center"><h4>'.'Ah ocurrido un error'.'</h4></div>']);
                    $this->load->view("footer");
                }
            } else {
                $paramsNew["fechaFin"]=null;
                $reestablecerEstado=$this->TenerEstadoUsuario_model->add_tenerEstadoUsuario($paramsNew);
            }
        }
        /*  $usuario = $this->Usuario_model->post_usuario($nombreUsuario);
         if (isset($usuario['nombreUsuario'])) {
             if ($this->Usuario_model->darBaja_usuario($usuario['nombreUsuario'])) {
             } else {
                 echo "No se ha podido dar de baja";
             };
         //redirect("usuario/index");
         } else {
             show_error('El usuario no existe');
         } */
    }
}
