<?php

/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
 
class Archivo_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get archivo by idArchivo
     */
    public function get_archivo($idArchivo)
    {
        return $this->db->get_where('archivo', array('idArchivo'=>$idArchivo))->row_array();
    }
        
    /*
     * Get all archivo
     */
    public function get_all_archivo($filters=array())
    {
      
            $this->db->where($filters);
        

        $this->db->order_by('idArchivo', 'asc');
        return $this->db->get('archivo')->result_array();
    }
        
    /*
     * function to add new archivo
     */
    public function add_archivo($params)
    {
        $this->db->insert('archivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update archivo
     */
    public function update_archivo($idArchivo,$params)
    {
        $this->db->where('idArchivo', $idArchivo);
        return $this->db->update('archivo', $params);
    }
    
    /*
     * function to delete archivo
     */
    public function delete_archivo($idArchivo)
    {
        return $this->db->delete('archivo', array('idArchivo'=>$idArchivo));
    }
}
