<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comentario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comentario by idComentario
     */
    function get_comentario($idComentario)
    {
        return $this->db->get_where('comentario',array('idComentario'=>$idComentario))->row_array();
    }
    
    /*
     * Get all comentario count
     */
    function get_all_comentario_count($params=array())
    {
        $this->db->where($params);
        $this->db->from('comentario');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all comentario
     */
    function get_all_comentario($params = array())
    {
        $this->db->order_by('idComentario', 'desc');
        if(isset($params["limit"]) && isset($params['offset']))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }else{
            $this->db->where($params);
        }
        return $this->db->get('comentario')->result_array();
    }
        
    /*
     * function to add new comentario
     */
    function add_comentario($params)
    {
        $this->db->insert('comentario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comentario
     */
    function update_comentario($idComentario,$params)
    {
        $this->db->where('idComentario',$idComentario);
        return $this->db->update('comentario',$params);
    }
    
    /*
     * function to delete comentario
     */
    function delete_comentario($idComentario)
    {
        return $this->db->delete('comentario',array('idComentario'=>$idComentario));
    }
}
