<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comentario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comentario by idComentario
     */
    function get_comentario($idComentario)
    {
        return $this->db->get_where('comentario',array('idComentario'=>$idComentario))->row_array();
    }
        
    /*
     * Get all comentario
     */
    function get_all_comentario()
    {
        $this->db->order_by('idComentario', 'desc');
        return $this->db->get('comentario')->result_array();
    }
        
    /*
     * function to add new comentario
     */
    function add_comentario($params)
    {
        $this->db->insert('comentario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comentario
     */
    function update_comentario($idComentario,$params)
    {
        $this->db->where('idComentario',$idComentario);
        return $this->db->update('comentario',$params);
    }
    
    /*
     * function to delete comentario
     */
    function delete_comentario($idComentario)
    {
        return $this->db->delete('comentario',array('idComentario'=>$idComentario));
    }
}
