<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estadorecurso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estadorecurso by nombre
     */
    function get_estadorecurso($nombre)
    {
        return $this->db->get_where('estadoRecurso',array('nombre'=>$nombre))->row_array();
    }
    
    /*
     * Get all estadorecurso count
     */
    function get_all_estadorecurso_count()
    {
        $this->db->from('estadoRecurso');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all estadorecurso
     */
    function get_all_estadorecurso($params = array())
    {
        $this->db->order_by('nombre', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('estadoRecurso')->result_array();
    }
        
    /*
     * function to add new estadorecurso
     */
    function add_estadorecurso($params)
    {
        $this->db->insert('estadoRecurso',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estadorecurso
     */
    function update_estadorecurso($nombre,$params)
    {
        $this->db->where('nombre',$nombre);
        return $this->db->update('estadoRecurso',$params);
    }
    
    /*
     * function to delete estadorecurso
     */
    function delete_estadorecurso($nombre)
    {
        return $this->db->delete('estadoRecurso',array('nombre'=>$nombre));
    }
}
