<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estadousuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estadousuario by nombre
     */
    function get_estadousuario($nombre)
    {
        return $this->db->get_where('estadoUsuario',array('nombre'=>$nombre))->row_array();
    }
        
    /*
     * Get all estadousuario
     */
    function get_all_estadousuario()
    {
        $this->db->order_by('nombre', 'desc');
        return $this->db->get('estadoUsuario')->result_array();
    }
        
    /*
     * function to add new estadousuario
     */
    function add_estadousuario($params)
    {
        $this->db->insert('estadoUsuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estadousuario
     */
    function update_estadousuario($nombre,$params)
    {
        $this->db->where('nombre',$nombre);
        return $this->db->update('estadoUsuario',$params);
    }
    
    /*
     * function to delete estadousuario
     */
    function delete_estadousuario($nombre)
    {
        return $this->db->delete('estadoUsuario',array('nombre'=>$nombre));
    }
}
