<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
 
class Nivel_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nivel by nombre
     */
    public function get_nivel($nombre)
    {
        return $this->db->get_where('nivel', array('nombre'=>$nombre))->row_array();
    }
        
    /*
     * Get all nivel
     */
    public function get_all_nivel()
    {
        $this->db->order_by('nombre', 'asc');
        return $this->db->get('nivel')->result_array();
    }
        
    /*
     * function to add new nivel
     */
    public function add_nivel($params)
    {
        $this->db->insert('nivel', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nivel
     */
    public function update_nivel($nombre, $params)
    {
        $this->db->where('nombre', $nombre);
        return $this->db->update('nivel', $params);
    }
    
    /*
     * function to delete nivel
     */
    public function delete_nivel($nombre)
    {
        return $this->db->delete('nivel', array('nombre'=>$nombre));
    }
}
