<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
 
class Rol_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rol by nombre
     */
    public function get_rol($nombre)
    {
        return $this->db->get_where('rol', array('nombre'=>$nombre))->row_array();
    }
        
    /*
     * Get all rol
     */
    public function get_all_rol()
    {
        $this->db->order_by('nombre', 'desc');
        return $this->db->get('rol')->result_array();
    }
        
    /*
     * function to add new rol
     */
    public function add_rol($params)
    {
        $this->db->insert('rol', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rol
     */
    public function update_rol($nombre, $params)
    {
        $this->db->where('nombre', $nombre);
        return $this->db->update('rol', $params);
    }
    
    /*
     * function to delete rol
     */
    public function delete_rol($nombre)
    {
        return $this->db->delete('rol', array('nombre'=>$nombre));
    }
}
