<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tenerestadorecurso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tenerestadorecurso by hora
     */
    function get_tenerestadorecurso($params)
    {
        return $this->db->get_where('tenerEstadoRecurso',$params)->row_array();
    }
    
    /*
     * Get all tenerestadorecurso count
     */
    function get_all_tenerestadorecurso_count()
    {
        $this->db->from('tenerEstadoRecurso');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tenerestadorecurso
     */
    function get_all_tenerestadorecurso($params = array())
    {
        $this->db->order_by('hora', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tenerEstadoRecurso')->result_array();
    }
        
    /*
     * function to add new tenerestadorecurso
     */
    function add_tenerestadorecurso($params)
    {
        $this->db->insert('tenerEstadoRecurso',$params);
        return $this->db->insert_id();
    }
    
  /*
     * function to update tenerEstadoUsuario
     */
    public function update_tenerestadorecurso($params=array(), $where=array())
    {
        foreach($where as $key=>$value){
            $this->db->where($key, $value);
        }
        return $this->db->update('tenerEstadoRecurso', $params);
    }
    
    /*
     * function to delete tenerestadorecurso
     */
    function delete_tenerestadorecurso($hora)
    {
        return $this->db->delete('tenerEstadoRecurso',array('hora'=>$hora));
    }
}
