<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tienerol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tienerol by nombreUsuario
     */
    function get_tienerol($nombreUsuario,$params=array())
    {
        if(count($params)>0){
            $params["nombreUsuario"]=$nombreUsuario;
            $rolActual=$this->db->get_where('tieneRol',$params)->row_array();
        }else{
            $rolActual=$this->db->get_where('tieneRol',array('nombreUsuario'=>$nombreUsuario))->row_array();
        }
        return $rolActual;
    }
        
    /*
     * Get all tienerol
     */
    function get_all_tienerol()
    {
        $this->db->order_by('nombreUsuario', 'desc');
        return $this->db->get('tieneRol')->result_array();
    }
        
    /*
     * function to add new tienerol
     */
    function add_tienerol($params)
    {
        $this->db->insert('tieneRol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tienerol
     */
    function update_tienerol($nombreUsuario,$params)
    {
        $this->db->where('nombreUsuario',$nombreUsuario);
        return $this->db->update('tieneRol',$params);
    }
    
    /*
     * function to delete tienerol
     */
    function delete_tienerol($nombreUsuario)
    {
        return $this->db->delete('tieneRol',array('nombreUsuario'=>$nombreUsuario));
    }
}
