<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    public function __construct()
        {
        parent::__construct();
    }
    
    /*
     * Get usuario by nombreUsuario
     */
    public function get_usuario($nombreUsuario, $params=array())
    {
        if (count($params)>0) {
            $params['nombreUsuario']=$nombreUsuario;
            $user=$this->db->get_where('usuario', $params)->row_array();
        } else {
            $user= $this->db->get_where('usuario', array('nombreUsuario'=>$nombreUsuario))->row_array();
            echo "<script>alert(\"no\")</script>";
        }
        return $user;
    }
        
    /*
     * Get all usuario
     */
    public function get_all_usuario()
    {
        $this->db->order_by('nombreUsuario', 'desc');
        return $this->db->get('usuario')->result_array();
    }
        
    /*
     * function to add new usuario
     */
    public function add_usuario($params)
    {
        if (!$this->db->insert('usuario', $params)) {
            $return= false;
        } else {
            $return= true;
        }
        return $return;
    }
    
    /*
     * function to update usuario
     */
    public function update_usuario($nombreUsuario, $params)
    {
        $this->db->where('nombreUsuario', $nombreUsuario);
        return $this->db->update('usuario', $params);
    }
    
    /*
     * function to delete usuario
     */
    public function delete_usuario($nombreUsuario)
    {
        return $this->db->delete('usuario', array('nombreUsuario'=>$nombreUsuario));
    }
}
